networks:
  kong-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/app.dockerfile
    container_name: app
    networks:
      kong-net:
        ipv4_address: 192.168.100.10
  kong:
    image: kong:3.6
    container_name: kong
    ports:
      - "8000:8000"   # Proxy (HTTP)
      #- "8001:8001"   # Admin API
    depends_on:
      - app
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    networks:
      kong-net:
        ipv4_address: 192.168.100.11
