services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - ./www:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
