networks:
  intranet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

  springapp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24

  phpapp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24

services:
  phpapp:
    build:
      context: phpapp
    container_name: phpapp
    volumes:
      - ../phpapp:/var/www/html
    networks:
      phpapp-net:
        ipv4_address: 192.168.102.10
    #ports:
    #  - 8080:80
  springapp:
    build:
      context: ..
      dockerfile: .container/springapp.dockerfile
    container_name: springapp
    networks:
      springapp-net:
        ipv4_address: 192.168.101.10
  phpapp-kong:
    image: kong:3.6
    container_name: phpapp-kong
    depends_on:
      - phpapp
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/phpapp.yml:/etc/kong/kong.yml:ro
    networks:
      phpapp-net:
        ipv4_address: 192.168.102.11
    ports:
      - "8001:8000"   # Proxy (HTTP)
  springapp-kong:
    image: kong:3.6
    container_name: springapp-kong
    depends_on:
      - springapp
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/springapp.yml:/etc/kong/kong.yml:ro
    networks:
      springapp-net:
        ipv4_address: 192.168.101.11
  central-kong:
    image: kong:3.6
    container_name: central-kong
    ports:
      - "8000:8000"   # Proxy (HTTP)
      #- "8001:8001"   # Admin API
    depends_on:
      - springapp-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/central.yml:/etc/kong/kong.yml:ro
    networks:
      intranet:
        ipv4_address: 192.168.100.10
      springapp-net:
        ipv4_address: 192.168.101.12
      phpapp-net:
        ipv4_address: 192.168.102.12